import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
    
    <div className={styles.hero}>
         <h2 className={styles.holy}>THE WORD</h2>
                <h1 className={styles.bible}>
                    <a href="https://the-holy-bible.vercel.app/" target="_blank">OF GOD</a>
                </h1>
        
        <h1 className={styles.title}>
       I Peter 
        </h1>
         <div  className={styles.image}>
       <Image 
                                src="/wc_1peter.jpeg"
                                alt="1st peter word cloud blue"
                                height={900}
                                width={2000}
                                priority
                              />
           </div>                   
                          <div className={styles.nav}>           
      <a href="https://phillipians.vercel.app/">
             <Image 
                                src="/chevron-left.svg"
                                alt="Jesus"
                                 height={75}
                                width={75}
                                priority
                              />
       </a>

         <a href="#PayPalButton">
            <Image 
                                src="/chevron-down.svg"
                                alt="Jesus"
                                 height={75}
                                width={75}
                                priority
                              />
           
        </a> 
         <a href="https://first-thessalonians.vercel.app/">
           <Image 
                                src="/chevron-right.svg"
                                alt="Jesus"
                                 height={75}
                                width={75}
                                priority
                              />
           
        </a> 
         
               </div>
      <p className={styles.fund}>
                                  (I Peter 4:19)  
                                 "So then, those who suffer according to God’s will should commit themselves to their faithful Creator and continue to do good."                                  </p>
        <div className={styles.grid}>
          <div className={styles.card}>
            <h2 className={styles.chapter}>I Peter Chapter I</h2>
            <p>1 Peter, an apostle of Jesus Christ,

"To God’s elect, exiles scattered throughout the provinces of Pontus, Galatia, Cappadocia, Asia and Bithynia, 2 who have been chosen according to the foreknowledge of God the Father, through the sanctifying work of the Spirit, to be obedient to Jesus Christ and sprinkled with his blood:

Grace and peace be yours in abundance.

Praise to God for a Living Hope
3 Praise be to the God and Father of our Lord Jesus Christ! In his great mercy he has given us new birth into a living hope through the resurrection of Jesus Christ from the dead, 4 and into an inheritance that can never perish, spoil or fade. This inheritance is kept in heaven for you, 5 who through faith are shielded by God’s power until the coming of the salvation that is ready to be revealed in the last time. 6 In all this you greatly rejoice, though now for a little while you may have had to suffer grief in all kinds of trials. 7 These have come so that the proven genuineness of your faith—of greater worth than gold, which perishes even though refined by fire—may result in praise, glory and honor when Jesus Christ is revealed. 8 Though you have not seen him, you love him; and even though you do not see him now, you believe in him and are filled with an inexpressible and glorious joy, 9 for you are receiving the end result of your faith, the salvation of your souls.

10 Concerning this salvation, the prophets, who spoke of the grace that was to come to you, searched intently and with the greatest care, 11 trying to find out the time and circumstances to which the Spirit of Christ in them was pointing when he predicted the sufferings of the Messiah and the glories that would follow. 12 It was revealed to them that they were not serving themselves but you, when they spoke of the things that have now been told you by those who have preached the gospel to you by the Holy Spirit sent from heaven. Even angels long to look into these things.

Be Holy
13 Therefore, with minds that are alert and fully sober, set your hope on the grace to be brought to you when Jesus Christ is revealed at his coming. 14 As obedient children, do not conform to the evil desires you had when you lived in ignorance. 15 But just as he who called you is holy, so be holy in all you do; 16 for it is written: “Be holy, because I am holy.”[a]

17 Since you call on a Father who judges each person’s work impartially, live out your time as foreigners here in reverent fear. 18 For you know that it was not with perishable things such as silver or gold that you were redeemed from the empty way of life handed down to you from your ancestors, 19 but with the precious blood of Christ, a lamb without blemish or defect. 20 He was chosen before the creation of the world, but was revealed in these last times for your sake. 21 Through him you believe in God, who raised him from the dead and glorified him, and so your faith and hope are in God.

22 Now that you have purified yourselves by obeying the truth so that you have sincere love for each other, love one another deeply, from the heart.[b] 23 For you have been born again, not of perishable seed, but of imperishable, through the living and enduring word of God. 24 For,

“All people are like grass,
    and all their glory is like the flowers of the field;
the grass withers and the flowers fall,
25     but the word of the Lord endures forever.”

And this is the word that was preached to you."

</p>
          </div>

          <div className={styles.card}>
             <h2 className={styles.chapter}>Colassians Chapter II</h2>
            <p>2 I want you to know how hard I am contending for you and for those at Laodicea, and for all who have not met me personally. 2 My goal is that they may be encouraged in heart and united in love, so that they may have the full riches of complete understanding, in order that they may know the mystery of God, namely, Christ, 3 in whom are hidden all the treasures of wisdom and knowledge. 4 I tell you this so that no one may deceive you by fine-sounding arguments. 5 For though I am absent from you in body, I am present with you in spirit and delight to see how disciplined you are and how firm your faith in Christ is.

Spiritual Fullness in Christ
6 So then, just as you received Christ Jesus as Lord, continue to live your lives in him, 7 rooted and built up in him, strengthened in the faith as you were taught, and overflowing with thankfulness.

8 See to it that no one takes you captive through hollow and deceptive philosophy, which depends on human tradition and the elemental spiritual forces[a] of this world rather than on Christ.

9 For in Christ all the fullness of the Deity lives in bodily form, 10 and in Christ you have been brought to fullness. He is the head over every power and authority. 11 In him you were also circumcised with a circumcision not performed by human hands. Your whole self ruled by the flesh[b] was put off when you were circumcised by[c] Christ, 12 having been buried with him in baptism, in which you were also raised with him through your faith in the working of God, who raised him from the dead.

13 When you were dead in your sins and in the uncircumcision of your flesh, God made you[d] alive with Christ. He forgave us all our sins, 14 having canceled the charge of our legal indebtedness, which stood against us and condemned us; he has taken it away, nailing it to the cross. 15 And having disarmed the powers and authorities, he made a public spectacle of them, triumphing over them by the cross.[e]

Freedom From Human Rules
16 Therefore do not let anyone judge you by what you eat or drink, or with regard to a religious festival, a New Moon celebration or a Sabbath day. 17 These are a shadow of the things that were to come; the reality, however, is found in Christ. 18 Do not let anyone who delights in false humility and the worship of angels disqualify you. Such a person also goes into great detail about what they have seen; they are puffed up with idle notions by their unspiritual mind. 19 They have lost connection with the head, from whom the whole body, supported and held together by its ligaments and sinews, grows as God causes it to grow.

20 Since you died with Christ to the elemental spiritual forces of this world, why, as though you still belonged to the world, do you submit to its rules: 21 “Do not handle! Do not taste! Do not touch!”? 22 These rules, which have to do with things that are all destined to perish with use, are based on merely human commands and teachings. 23 Such regulations indeed have an appearance of wisdom, with their self-imposed worship, their false humility and their harsh treatment of the body, but they lack any value in restraining sensual indulgence.</p>
          </div>

          <div
            className={styles.card}
          >
            <h2 className={styles.chapter}>Colassians Chapter III</h2>
            <p>Living as Those Made Alive in Christ
3 Since, then, you have been raised with Christ, set your hearts on things above, where Christ is, seated at the right hand of God. 2 Set your minds on things above, not on earthly things. 3 For you died, and your life is now hidden with Christ in God. 4 When Christ, who is your[a] life, appears, then you also will appear with him in glory.

5 Put to death, therefore, whatever belongs to your earthly nature: sexual immorality, impurity, lust, evil desires and greed, which is idolatry. 6 Because of these, the wrath of God is coming.[b] 7 You used to walk in these ways, in the life you once lived. 8 But now you must also rid yourselves of all such things as these: anger, rage, malice, slander, and filthy language from your lips. 9 Do not lie to each other, since you have taken off your old self with its practices 10 and have put on the new self, which is being renewed in knowledge in the image of its Creator. 11 Here there is no Gentile or Jew, circumcised or uncircumcised, barbarian, Scythian, slave or free, but Christ is all, and is in all.

12 Therefore, as God’s chosen people, holy and dearly loved, clothe yourselves with compassion, kindness, humility, gentleness and patience. 13 Bear with each other and forgive one another if any of you has a grievance against someone. Forgive as the Lord forgave you. 14 And over all these virtues put on love, which binds them all together in perfect unity.

15 Let the peace of Christ rule in your hearts, since as members of one body you were called to peace. And be thankful. 16 Let the message of Christ dwell among you richly as you teach and admonish one another with all wisdom through psalms, hymns, and songs from the Spirit, singing to God with gratitude in your hearts. 17 And whatever you do, whether in word or deed, do it all in the name of the Lord Jesus, giving thanks to God the Father through him.

Instructions for Christian Households
18 Wives, submit yourselves to your husbands, as is fitting in the Lord.

19 Husbands, love your wives and do not be harsh with them.

20 Children, obey your parents in everything, for this pleases the Lord.

21 Fathers,[c] do not embitter your children, or they will become discouraged.

22 Slaves, obey your earthly masters in everything; and do it, not only when their eye is on you and to curry their favor, but with sincerity of heart and reverence for the Lord. 23 Whatever you do, work at it with all your heart, as working for the Lord, not for human masters, 24 since you know that you will receive an inheritance from the Lord as a reward. It is the Lord Christ you are serving. 25 Anyone who does wrong will be repaid for their wrongs, and there is no favoritism.

</p>
          </div>

          <div
            className={styles.card}
          >
             <h2 className={styles.chapter}>Colassians Chapter IV</h2>
            <p>
            4 Masters, provide your slaves with what is right and fair, because you know that you also have a Master in heaven.

Further Instructions
2 Devote yourselves to prayer, being watchful and thankful. 3 And pray for us, too, that God may open a door for our message, so that we may proclaim the mystery of Christ, for which I am in chains. 4 Pray that I may proclaim it clearly, as I should. 5 Be wise in the way you act toward outsiders; make the most of every opportunity. 6 Let your conversation be always full of grace, seasoned with salt, so that you may know how to answer everyone.

Final Greetings
7 Tychicus will tell you all the news about me. He is a dear brother, a faithful minister and fellow servant[a] in the Lord. 8 I am sending him to you for the express purpose that you may know about our[b] circumstances and that he may encourage your hearts. 9 He is coming with Onesimus, our faithful and dear brother, who is one of you. They will tell you everything that is happening here.

10 My fellow prisoner Aristarchus sends you his greetings, as does Mark, the cousin of Barnabas. (You have received instructions about him; if he comes to you, welcome him.) 11 Jesus, who is called Justus, also sends greetings. These are the only Jews[c] among my co-workers for the kingdom of God, and they have proved a comfort to me. 12 Epaphras, who is one of you and a servant of Christ Jesus, sends greetings. He is always wrestling in prayer for you, that you may stand firm in all the will of God, mature and fully assured. 13 I vouch for him that he is working hard for you and for those at Laodicea and Hierapolis. 14 Our dear friend Luke, the doctor, and Demas send greetings. 15 Give my greetings to the brothers and sisters at Laodicea, and to Nympha and the church in her house.

16 After this letter has been read to you, see that it is also read in the church of the Laodiceans and that you in turn read the letter from Laodicea.

17 Tell Archippus: “See to it that you complete the ministry you have received in the Lord.”

18 I, Paul, write this greeting in my own hand. Remember my chains. Grace be with you.
            </p>
          </div>
        </div>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
